name: Black

on: [push]

jobs:
  black-lint:
    name: Black
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: rickstaa/action-black@v1
      id: action_black
      with:
        black_args: ". --check --verbose --line-length=120"

  build-n-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/black-junit
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Build wheel and install
        run: |
          python -m pip install --user --upgrade build
          python -m build
          #find ./dist/*.whl | xargs pip install
          #python simple_test.py
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
